### ISSUE TITLE
Pinout of footprints is wrong

### ISSUE THREAD

**Issue by KLelong** [rubienr/wemos-d1-mini-kicad#2]
I used your library, and I found that the pins of the footprints are wrong, compared to the schematic. If you turn the footprint 180 degrees it's OK, but then the outline is wrong.
Luckily I checked, so no harm done.

**Comment by rubienr** [comment]
Thank you @KLelong for the report. The symbol's pinout and modules' pins have been turned 180°. I found the reason why the layout was wrong. My mistake I referred to the [LOLIN](https://docs.wemos.cc/en/latest/d1/d1_mini.html) D1 mini instead of the [original](https://escapequotes.net/esp8266-wemos-d1-mini-pins-and-diagram/) one. The difference is: LOLIN has the USB socket above the PCB, original below. This let me flip the device which was wrong.

Feel free to re-open the issue if you still have troubles with updated the library.
